In [42]:
import requests
import json

def get_runner_ids(eventCode="M2024", place1=48000, place2=48010):
    url = 'https://rmsprodapi.nyrr.org/api/v2/runners/finishers-filter'
    header = {"content-type": "application/json;charset=UTF-8"}
    j = {"eventCode": eventCode, "overallPlaceFrom": place1, "overallPlaceTo": place2,
         "sortColumn": "overallTime", "sortDescending":"false"
}
    response = requests.post(url, headers=header, json=j, allow_redirects=True)
    assert response.status_code == 200
    print(response)
    d = json.loads(response.text)
    print(d["totalItems"], len(d["items"]), d["items"][0]["runnerId"])
    return d

def get_splits(runner_id=42948497):
    url = 'https://rmsprodapi.nyrr.org/api/v2/runners/resultDetails'
    header = {"content-type": "application/json;charset=UTF-8"}
    response = requests.post(url, headers=header, json={"runnerId": str(runner_id)}, allow_redirects=True)
    assert response.status_code == 200, f"Response Code = {response.status_code}"
    d = json.loads(response.text)
    assert d["details"], f"No data specified, d = {d}"
    return d

In [ ]:
get_runner_ids(eventCode="M2023", place1=1, place2=5)

int

In [43]:
get_splits(runner_id=43928778)

AssertionError: No data specified, d = {'details': None, 'success': True, 'message': None}

In [44]:
import time
import pandas as pd
feats = ["runnerId", "bib", "firstName", "lastName", "age", "gender", "city", "countryCode"]

def load_data(last_runner=522, eventCode="M2024"):
    tables = []
    for i in range(1, last_runner, 100):
        place1, place2 = i, i+99
        data = get_runner_ids(eventCode, place1, place2)
        table = pd.DataFrame(data['items'])[feats]
        tables.append(table)
        if (i - 1) % 1000 == 0:
            time.sleep(1)
            print("loaded", i - 1)

    return tables

In [ ]:
tables = load_data(last_runner=47745, eventCode="M2022")
pd.concat(tables)

In [5]:
# pd.concat(tables).to_csv("raw_data/nyc/runnerData22.csv", index=False)

In [137]:
# ids = pd.read_csv("raw_data/nyc/runnerData24.csv")["runnerId"]

In [45]:
data24 = pd.read_csv("raw_data/nyc/runnerData23.csv")
ids = list(data24["runnerId"])


num_runners = 1000
tables2 = []

for j, id in enumerate(ids):
#   try:
    i = j + 1
    splits = get_splits(id)['details']['splitResults']
    dt = {dct["splitCode"]: dct["time"] for dct in splits}
    ser = pd.Series(dt)
    ser["id"] = id
    tables2.append(ser)
    # tables2.append(dt)
    if i % 50 == 0:
        print("loaded", i)
        time.sleep(2)
    if i == num_runners:
        break
#   except Exception as e:
#      print(i, e)
#      continue

loaded 50
loaded 100
loaded 150
loaded 200

AssertionError: Response Code = 429

In [46]:
i

234

In [15]:
s = pd.Series({dct["splitCode"]: dct["time"] for dct in get_splits(id)['details']['splitResults']})
s['id']

5K       0:18:38
10K      0:37:09
15K      0:55:29
20K      1:13:54
HALF     1:17:57
25K      1:32:41
30K      1:51:19
20M      1:59:58
35K      2:11:26
40K      2:32:25
25.2M    2:34:45
26M      2:40:02
MAR      2:41:25
dtype: object

In [5]:
pd.DataFrame(tables2)

,5K,10K,15K,20K,HALF,25K,30K,20M,35K,40K,26M,MAR,id,25.2M
0,0:15:29,0:30:40,0:45:04,0:59:34,1:02:45,1:14:15,1:28:22,1:34:38,1:42:51,1:58:08,2:03:53,2:04:58,42307341,NaN
1,0:15:28,0:30:38,0:45:04,0:59:34,1:02:46,1:14:15,1:28:48,1:35:29,1:44:05,2:00:06,2:05:54,2:06:57,42311423,NaN
2,0:15:31,0:30:40,0:45:06,0:59:39,1:02:52,1:14:37,1:29:07,1:35:42,1:44:24,2:00:20,2:06:08,2:07:11,42307340,2:02:07
3,0:15:29,0:30:38,0:45:05,0:59:36,1:02:47,1:14:34,1:29:40,1:36:37,1:45:40,2:03:23,2:09:11,2:10:21,42317876,2:05:14
4,0:15:31,0:30:37,0:45:29,1:00:33,1:03:56,1:16:28,1:31:48,1:38:43,1:47:42,2:03:35,2:09:21,2:10:25,42304333,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
707,0:20:49,0:41:12,1:01:44,1:22:29,1:27:04,1:43:34,2:04:01,2:13:17,2:25:09,2:47:26,2:55:22,2:56:52,42325948,2:49:54
708,0:20:47,0:41:51,1:02:58,1:24:13,1:28:55,1:46:03,2:07:13,2:16:10,2:28:01,2:48:46,2:55:39,2:56:53,42307211,2:50:57
709,0:19:28,0:39:12,0:59:05,1:19:13,1:23:42,1:40:12,2:00:49,2:10:22,2:22:57,2:46:20,2:55:10,2:56:53,42315503,2:48:55
710,0:20:36,0:41:19,1:02:04,1:22:57,1:27:33,1:44:13,2:04:50,2:14:11,2:26:17,2:47:34,2:55:26,2:56:53,42329729,2:50:00
711,0:20:23,0:41:05,1:01:54,1:22:51,1:27:28,1:44:09,2:04:41,2:13:52,2:25:52,2:47:28,2:55:21,2:56:55,42312346,2:49:56

In [18]:
ids[0], 43091563

(42948497, 43091563)

In [169]:
d1 = data24.iloc[:50, :]
d2 = pd.DataFrame(tables2)
pd.concat([d1, d2], axis=1)

,runnerId,bib,firstName,lastName,age,gender,city,countryCode,5K,10K,...,20K,HALF,25K,30K,20M,35K,40K,25.2M,26M,MAR
0,42948497,7.0,Abdi,Nageeye,35,M,Nijmegen,NLD,0:16:02,0:31:28,...,1:02:21,1:05:35,1:17:48,1:31:58,1:38:17,1:46:20,2:01:10,2:02:52,2:06:36,2:07:39
1,42953047,3.0,Evans,Chebet,35,M,Kapsabet,KEN,0:16:00,0:31:29,...,1:02:20,1:05:34,1:17:48,1:31:57,1:38:17,1:46:20,2:01:10,2:02:52,2:06:39,2:07:45
2,42943555,2.0,Albert,Korir,30,M,Kapkitony,KEN,0:16:00,0:31:28,...,1:02:20,1:05:34,1:17:48,1:31:57,1:38:18,1:46:28,2:01:26,2:03:05,2:06:55,2:08:00
3,42940461,1.0,Tamirat,Tola,33,M,Addis Ababa,ETH,0:16:02,0:31:28,...,1:02:20,1:05:34,1:17:48,1:31:57,1:38:17,1:46:25,2:01:24,2:03:06,2:07:04,2:08:12
4,42934706,6.0,Geoffrey,Kamworor,31,M,Kapchorwa District,KEN,0:16:01,0:31:29,...,1:02:20,1:05:34,1:17:48,1:31:57,1:38:17,1:46:21,2:01:35,2:03:24,2:07:39,2:08:50
5,42950271,10.0,Conner,Mantz,27,M,Provo,USA,0:15:59,0:31:30,...,1:02:24,1:05:35,1:17:48,1:32:14,1:38:53,1:47:24,2:02:38,2:04:17,2:07:58,2:09:00
6,42943637,11.0,Clayton,Young,31,M,Provo,USA,0:16:01,0:31:30,...,1:02:23,1:05:36,1:17:49,1:32:31,1:39:09,1:47:35,2:02:41,2:04:23,2:08:15,2:09:21
7,42964374,9.0,Abel,Kipchumba,30,M,Iten,KEN,0:15:59,0:31:28,...,1:02:19,1:05:35,1:17:49,1:32:15,1:38:56,1:47:34,2:03:28,2:05:21,2:09:33,2:10:39
8,42983034,4.0,Bashir,Abdi,35,M,Ghent,BEL,0:16:03,0:31:31,...,1:02:22,1:05:34,1:17:49,1:32:44,1:39:33,1:48:12,2:03:56,2:05:41,2:09:36,2:10:39
9,42983033,20.0,Cj,Albertson,31,M,Fresno,USA,0:16:02,0:31:30,...,1:02:17,1:05:39,1:17:55,1:32:51,1:39:44,1:48:27,2:04:13,2:05:58,2:09:54,2:10:57
10,42953316,32.0,Ryan,Ford,27,M,Boone,USA,0:16:05,0:31:34,...,1:02:24,1:05:49,1:18:03,1:33:14,1:40:02,1:48:43,2:04:23,2:06:11,2:10:07,2:11:08
11,42983036,21.0,Colin,Bennie,29,M,San Francisco,USA,0:16:04,0:31:34,...,1:02:25,1:05:48,1:18:03,1:33:22,1:40:09,1:48:49,2:04:21,2:06:08,2:10:08,2:11:16
12,42950270,27.0,Frank,Lara,29,M,Boulder,USA,0:16:03,0:31:30,...,1:02:23,1:05:40,1:17:48,1:32:52,1:39:44,1:48:27,2:04:20,2:06:08,2:10:13,2:11:21
13,42931209,16.0,Jonny,Mellor,37,M,Liverpool,GBR,0:16:01,0:31:30,...,1:02:22,1:05:35,1:17:50,1:32:52,1:39:43,1:48:27,2:04:21,2:06:11,2:10:15,2:11:22
14,42946945,12.0,Rory,Linkletter,28,M,Flagstaff,USA,0:16:00,0:31:31,...,1:02:22,1:05:40,1:17:56,1:32:51,1:39:45,1:48:31,2:04:40,2:06:30,2:10:36,2:11:45
15,42983039,23.0,Wesley,Kiptoo,28,M,Flagstaff,USA,0:16:00,0:31:29,...,1:02:20,1:05:35,1:17:48,1:31:59,1:38:28,1:47:09,2:03:49,2:05:50,2:10:34,2:11:58
16,42938080,17.0,Futsum,Zienasellassie,31,M,Flagstaff,USA,0:16:05,0:31:29,...,1:02:22,1:05:44,1:17:56,1:33:14,1:40:04,1:48:59,2:05:24,2:07:14,2:11:22,2:12:32
17,42983043,24.0,Joel,Reichow,31,M,Saint Paul,USA,0:16:05,0:31:33,...,1:02:24,1:05:49,1:18:06,1:33:34,1:40:42,1:49:46,2:06:02,2:07:48,2:11:50,2:12:52
18,42948496,15.0,Elkanah,Kibet,41,M,Colorado Springs,USA,0:16:01,0:31:27,...,1:02:22,1:05:39,1:17:56,1:33:40,1:40:51,1:49:53,2:06:18,2:08:10,2:12:19,2:13:27
19,42983032,30.0,Ryan,Eiler,38,M,Boston,USA,0:16:03,0:31:32,...,1:02:24,1:05:48,1:18:12,1:33:41,1:40:50,1:49:56,2:06:18,2:08:11,2:12:24,2:13:36
20,42936055,22.0,Teshome,Mekonen,29,M,New York,USA,0:16:03,0:31:30,...,1:02:21,1:05:35,1:17:49,1:32:31,1:39:10,1:47:51,2:05:30,2:07:41,2:12:51,2:14:12
21,42983037,8.0,Addisu,Gobena,20,M,Addis Ababa,ETH,0:16:01,0:31:28,...,1:02:20,1:05:33,1:17:48,1:32:29,1:39:25,1:48:48,2:06:54,2:08:59,2:13:34,2:14:49
22,42937549,14.0,Callum,Hawkins,32,M,Elderslie,GBR,0:16:04,0:31:33,...,1:03:00,1:06:30,1:19:23,1:35:17,1:42:18,1:51:24,2:07:58,2:09:50,2:14:03,2:15:12
23,42983038,26.0,Josh,Izewski,34,M,Boone,USA,0:16:02,0:31:28,...,1:02:24,1:05:45,1:18:36,1:34:44,1:42:19,1:52:29,2:09:27,2:11:22,2:15:44,2:16:58
24,42973854,612.0,Owen,Ritz,25,M,New York,USA,0:16:34,0:32:46,...,1:05:03,1:08:38,1:21:39,1:37:37,1:44:45,1:53:53,2:10:11,2:12:01,2:16:07,2:17:16
25,42966219,1274.0,Jake,Perrin,26,M,Bozeman,USA,0:16:08,0:32:11,...,1:04:39,1:08:17,1:21:19,1:37:28,1:44:37,1:53:54,2:10:31,2:12:25,2:16:36,2:17:46
26,42960933,38.0,Desta,Utura Gedo,28,M,Washington,USA,0:16:04,0:31:33,...,1:02:46,1:06:29,1:20:04,1:36:41,1:44:22,1:54:01,2:11:07,2:13:02,2:17:17,2:18:30
27,42982695,569.0,Dylan,Marx,32,M,San Diego,USA,0:16:25,0:32:31,...,1:05:00,1:08:37,1:21:40,1:37:49,1:45:08,1:54:38,2:11:23,2:13:17,2:17:31,2:18:42
28,42968084,614.0,Gavin,Glaza,24,M,Brighton,USA,0:16:59,0:33:47,...,1:06:48,1:10:33,1:23:47,1:40:01,1:47:10,1:56:08,2:12:08,2:13:57,2:17:59,2:19:05
29,42983035,31.0,Ser-Od,Bat-Ochir,43,M,Osaka,JPN,0:16:03,0:31:30,...,1:03:23,1:07:01,1:20:18,1:36:59,1:44:30,1:54:07,2:11:26,2:13:24,2:17:54,2:19:08
30,42967912,1204.0,Stepan,Kiselev,38,M,Cheboksary,RUS,0:16:13,0:32:26,...,1:04:42,1:08:19,1:21:19,1:37:30,1:44:56,1:54:25,2:11:32,2:13:31,2:17:59,2:19:13
31,42937548,29.0,Jared,Ward,36,M,Mapleton,USA,0:16:04,0:32:02,...,1:04:25,1:08:06,1:21:29,1:38:01,1:45:21,1:54:53,2:12:05,2:13:59,2:18:20,2:19:36
32,42942316,33.0,Scottie,Nelson,28,M,New York,USA,0:16:06,0:32:12,...,1:05:15,1:08:57,1:22:19,1:38:51,1:46:14,1:55:42,2:12:39,2:14:32,2:18:43,2:19:51
33,42964117,600.0,Terry,Tossman,28,M,Washington,USA,0:16:33,0:32:46,...,1:05:02,1:08:38,1:21:38,1:37:58,1:45:26,1:55:05,2:12:32,2:14:31,2:18:55,2:20:08
34,42964771,576.0,Connor,Mora,29,M,Chicago,USA,0:17:02,0:33:46,...,1:06:51,1:10:34,1:23:48,1:40:03,1:47:13,1:56:20,2:12:55,2:14:50,2:19:03,2:20:13
35,42966131,601.0,Esteban,Trujillo,39,M,Fort Collins,USA,0:16:52,0:33:15,...,1:06:27,1:10:08,1:23:16,1:39:19,1:46:41,1:55:58,2:13:04,2:15:00,2:19:27,2:20:39
36,42947012,1403.0,Hugo,Fry,27,M,London,GBR,0:16:24,0:33:00,...,1:06:12,1:09:54,1:23:19,1:39:52,1:47:17,1:56:48,2:14:01,2:15:57,2:20:21,2:21:33
37,42969408,1211.0,John,Borjesson,32,M,Falun,SWE,0:16:18,0:32:31,...,1:05:12,1:08:54,1:22:23,1:39:03,1:46:38,1:56:22,2:14:02,2:16:06,2:20:42,2:21:55
38,42970585,1231.0,Oscar,Acosta,36,M,Bogotá,COL,0:16:50,0:33:22,...,1:06:26,1:10:10,1:23:24,1:39:39,1:46:50,1:56:12,2:13:48,2:15:55,2:20:40,2:22:03
39,42941161,531.0,David,Gaertlein,32,M,Mainroth,DEU,0:16:41,0:33:18,...,1:06:28,1:10:12,1:23:36,1:40:09,1:47:35,1:57:04,2:14:24,2:16:24,2:20:51,2:22:05
40,42943626,610.0,Andrew,Gelston,34,M,Greystone Park,USA,0:16:52,0:33:44,...,1:06:53,1:10:37,1:23:52,1:40:24,1:47:47,1:57:18,2:14:45,2:16:45,2:21:14,2:22:29
41,42968026,671.0,Kanato,Goto,35,M,Princeton,USA,0:17:07,0:33:48,...,1:06:50,1:10:34,1:23:49,1:40:19,1:47:48,1:57:19,2:14:44,2:16:45,2:21:14,2:22:30
42,42934508,557.0,Ethan,Koreff,32,M,New York,USA,0:17:02,0:33:46,...,1:07:05,1:10:50,1:24:09,1:40:43,1:48:07,1:57:36,2:15:02,2:17:04,2:21:32,2:22:47
43,42963635,502.0,Derek,Alcorn,33,M,Littleton,USA,0:17:01,0:33:46,...,1:06:52,1:10:35,1:23:57,1:40:38,1:48:19,1:58:02,2:15:40,2:17:40,2:22:01,2:23:08
44,42966892,525.0,Nicolas,Dalmasso,36,M,Vincennes,FRA,0:16:31,0:32:46,...,1:05:35,1:09:22,1:22:59,1:39:52,1:47:32,1:57:27,2:15:23,2:17:27,2:21:58,2:23:13
45,42938815,514.0,Spencer,Bossi Johnson,29,M,Arlington,USA,0:17:02,0:33:47,...,1:06:52,1:10:35,1:23:57,1:40:37,1:48:11,1:57:50,2:15:15,2:17:18,2:21:58,2:23:14
46,42965607,526.0,Tom,Derr,32,M,Boulder,USA,0:16:33,0:32:45,...,1:05:57,1:09:44,1:23:16,1:39:49,1:47:21,1:57:11,2:15:16,2:17:23,2:22:05,2:23:21
47,42940762,611.0,William,Hague,30,M,Winnetka,USA,0:17:02,0:33:48,...,1:06:51,1:10:34,1:23:49,1:40:20,1:47:57,1:57:43,2:15:47,2:17:56,2:22:37,2:23:54
48,42940094,18.0,Nico,Montanez,31,M,Mammoth Lakes,USA,0:16:03,0:31:32,...,1:02:46,1:06:25,1:20:06,1:38:16,1:46:28,1:57:12,2:15:59,2:18:09,2:22:54,2:24:13
49,42949937,1299.0,Alexis,Garod,30,M,Lyon,FRA,0:16:54,0:33:31,...,1:06:43,1:10:30,1:24:11,1:41:03,1:48:43,1:58:31,2:16:23,2:18:24,2:22:58,2:24:15

In [167]:
pd.concat([d1, d2], axis=1)

,runnerId,bib,firstName,lastName,age,gender,city,countryCode,5K,10K,...,20K,HALF,25K,30K,20M,35K,40K,25.2M,26M,MAR
0,42948497,7.0,Abdi,Nageeye,35,M,Nijmegen,NLD,0:16:02,0:31:28,...,1:02:21,1:05:35,1:17:48,1:31:58,1:38:17,1:46:20,2:01:10,2:02:52,2:06:36,2:07:39
1,42953047,3.0,Evans,Chebet,35,M,Kapsabet,KEN,0:16:00,0:31:29,...,1:02:20,1:05:34,1:17:48,1:31:57,1:38:17,1:46:20,2:01:10,2:02:52,2:06:39,2:07:45
2,42943555,2.0,Albert,Korir,30,M,Kapkitony,KEN,0:16:00,0:31:28,...,1:02:20,1:05:34,1:17:48,1:31:57,1:38:18,1:46:28,2:01:26,2:03:05,2:06:55,2:08:00
3,42940461,1.0,Tamirat,Tola,33,M,Addis Ababa,ETH,0:16:02,0:31:28,...,1:02:20,1:05:34,1:17:48,1:31:57,1:38:17,1:46:25,2:01:24,2:03:06,2:07:04,2:08:12
4,42934706,6.0,Geoffrey,Kamworor,31,M,Kapchorwa District,KEN,0:16:01,0:31:29,...,1:02:20,1:05:34,1:17:48,1:31:57,1:38:17,1:46:21,2:01:35,2:03:24,2:07:39,2:08:50
5,42950271,10.0,Conner,Mantz,27,M,Provo,USA,0:15:59,0:31:30,...,1:02:24,1:05:35,1:17:48,1:32:14,1:38:53,1:47:24,2:02:38,2:04:17,2:07:58,2:09:00
6,42943637,11.0,Clayton,Young,31,M,Provo,USA,0:16:01,0:31:30,...,1:02:23,1:05:36,1:17:49,1:32:31,1:39:09,1:47:35,2:02:41,2:04:23,2:08:15,2:09:21
7,42964374,9.0,Abel,Kipchumba,30,M,Iten,KEN,0:15:59,0:31:28,...,1:02:19,1:05:35,1:17:49,1:32:15,1:38:56,1:47:34,2:03:28,2:05:21,2:09:33,2:10:39
8,42983034,4.0,Bashir,Abdi,35,M,Ghent,BEL,0:16:03,0:31:31,...,1:02:22,1:05:34,1:17:49,1:32:44,1:39:33,1:48:12,2:03:56,2:05:41,2:09:36,2:10:39
9,42983033,20.0,Cj,Albertson,31,M,Fresno,USA,0:16:02,0:31:30,...,1:02:17,1:05:39,1:17:55,1:32:51,1:39:44,1:48:27,2:04:13,2:05:58,2:09:54,2:10:57

In [82]:
marks = ["5K", "10K", "15K", "20K", "HALF", "25K", "30K", "35K", "40K", "MAR"]

In [10]:
d2 = get_runner_ids(230, 240)
a1 = [c["lastName"] for c in d2["items"]]
a1
# d

<Response [200]>

IndexError: list index out of range

In [11]:
d2

{'totalItems': 0, 'items': []}

In [9]:
test_id =d2['items'][0]["runnerId"]
d3 = get_splits(runner_id = test_id)
d3

IndexError: list index out of range

In [52]:
d3["details"]

{'runnerId': 42939236,
 'bib': '1300',
 'teamName': None,
 'iaaf': 'USA',
 'placeOverall': 230,
 'gunPlaceOverall': 237,
 'netPlaceOverall': 230,
 'timeOverall': '2:34:54',
 'gunTime': '2:35:34',
 'netTime': '2:34:54',
 'scoreByNetTime': True,
 'pace': '05:55',
 'placeGender': 209,
 'placeAgeGroup': 67,
 'ageGroupFromTo': '30-34',
 'timeAgeGrade': '2:34:54',
 'placeAgeGrade': 456,
 'percentAgeGrade': 79.38,
 'placeCountry': 137,
 'speed': 10.2,
 'photoUrl': 'https://www.marathonfoto.com/In?RaceOID=27042024F2&LastName=Harper&BibNumber=1300',
 'basnoPhotoUrl': '',
 'splitResults': [{'splitCode': '5K',
   'splitName': None,
   'time': '0:18:29',
   'pace': '05:57',
   'speed': 10.1,
   'distance': 3.11},
  {'splitCode': '10K',
   'splitName': None,
   'time': '0:36:37',
   'pace': '05:54',
   'speed': 10.2,
   'distance': 6.21},
  {'splitCode': '15K',
   'splitName': None,
   'time': '0:54:51',
   'pace': '05:54',
   'speed': 10.2,
   'distance': 9.32},
  {'splitCode': '20K',
   'splitName': None,
   'time': '1:13:01',
   'pace': '05:53',
   'speed': 10.2,
   'distance': 12.43},
  {'splitCode': 'HALF',
   'splitName': None,
   'time': '1:17:02',
   'pace': '05:53',
   'speed': 10.2,
   'distance': 13.1},
  {'splitCode': '25K',
   'splitName': None,
   'time': '1:31:36',
   'pace': '05:54',
   'speed': 10.2,
   'distance': 15.53},
  {'splitCode': '30K',
   'splitName': None,
   'time': '1:49:47',
   'pace': '05:54',
   'speed': 10.2,
   'distance': 18.64},
  {'splitCode': '20M',
   'splitName': None,
   'time': '1:57:47',
   'pace': '05:54',
   'speed': 10.2,
   'distance': 20.0},
  {'splitCode': '35K',
   'splitName': None,
   'time': '2:08:06',
   'pace': '05:54',
   'speed': 10.2,
   'distance': 21.75},
  {'splitCode': '40K',
   'splitName': None,
   'time': '2:26:38',
   'pace': '05:54',
   'speed': 10.2,
   'distance': 24.85},
  {'splitCode': '25.2M',
   'splitName': None,
   'time': '2:28:48',
   'pace': '05:54',
   'speed': 10.2,
   'distance': None},
  {'splitCode': '26M',
   'splitName': None,
   'time': '2:33:33',
   'pace': '05:55',
   'speed': 10.2,
   'distance': 26.0},
  {'splitCode': 'MAR',
   'splitName': None,
   'time': '2:34:54',
   'pace': '05:55',
   'speed': 10.2,
   'distance': 26.22}],
 'overallTotalPlaces': 55529,
 'genderTotalPlaces': 30701,
 'ageGroupTotalPlaces': 4756,
 'ageGradedTotalPlaces': 30701,
 'countryTotalPlaces': 33368}

In [35]:
import json
# url = 'https://rmsprodapi.nyrr.org/api/v2/runners/eventRunner'
url = 'https://rmsprodapi.nyrr.org/api/v2/runners/resultDetails'
j = {"eventCode": "M2024", "bib": "4"}
header = {"content-type": "application/json;charset=UTF-8"}
response = requests.post(url, headers=header, json=j, allow_redirects=True)
print(response)

<Response [200]>

In [23]:
json.loads(response.text)["details"]

{'runnerId': 42948497,
 'bib': '7',
 'teamName': 'NIKE',
 'iaaf': 'NED',
 'placeOverall': 1,
 'gunPlaceOverall': 1,
 'netPlaceOverall': 1,
 'timeOverall': '2:07:39',
 'gunTime': '2:07:39',
 'netTime': '2:07:39',
 'scoreByNetTime': True,
 'pace': '04:53',
 'placeGender': 1,
 'placeAgeGroup': 1,
 'ageGroupFromTo': '35-39',
 'timeAgeGrade': '2:06:57',
 'placeAgeGrade': 1,
 'percentAgeGrade': 96.86,
 'placeCountry': 1,
 'speed': 12.3,
 'photoUrl': 'https://www.marathonfoto.com/In?RaceOID=27042024F2&LastName=Nageeye&BibNumber=7',
 'basnoPhotoUrl': '',
 'splitResults': [{'splitCode': '5K',
   'splitName': None,
   'time': '0:16:02',
   'pace': '05:10',
   'speed': 11.6,
   'distance': 3.11},
  {'splitCode': '10K',
   'splitName': None,
   'time': '0:31:28',
   'pace': '05:04',
   'speed': 11.9,
   'distance': 6.21},
  {'splitCode': '15K',
   'splitName': None,
   'time': '0:46:55',
   'pace': '05:02',
   'speed': 11.9,
   'distance': 9.32},
  {'splitCode': '20K',
   'splitName': None,
   'time': '1:02:21',
   'pace': '05:01',
   'speed': 12.0,
   'distance': 12.43},
  {'splitCode': 'HALF',
   'splitName': None,
   'time': '1:05:35',
   'pace': '05:01',
   'speed': 12.0,
   'distance': 13.1},
  {'splitCode': '25K',
   'splitName': None,
   'time': '1:17:48',
   'pace': '05:01',
   'speed': 12.0,
   'distance': 15.53},
  {'splitCode': '30K',
   'splitName': None,
   'time': '1:31:58',
   'pace': '04:56',
   'speed': 12.2,
   'distance': 18.64},
  {'splitCode': '20M',
   'splitName': None,
   'time': '1:38:17',
   'pace': '04:55',
   'speed': 12.2,
   'distance': 20.0},
  {'splitCode': '35K',
   'splitName': None,
   'time': '1:46:20',
   'pace': '04:54',
   'speed': 12.3,
   'distance': 21.75},
  {'splitCode': '40K',
   'splitName': None,
   'time': '2:01:10',
   'pace': '04:53',
   'speed': 12.3,
   'distance': 24.85},
  {'splitCode': '25.2M',
   'splitName': None,
   'time': '2:02:52',
   'pace': '04:53',
   'speed': 12.3,
   'distance': None},
  {'splitCode': '26M',
   'splitName': None,
   'time': '2:06:36',
   'pace': '04:53',
   'speed': 12.3,
   'distance': 26.0},
  {'splitCode': 'MAR',
   'splitName': None,
   'time': '2:07:39',
   'pace': '04:53',
   'speed': 12.3,
   'distance': 26.22}],
 'overallTotalPlaces': 55529,
 'genderTotalPlaces': 30701,
 'ageGroupTotalPlaces': 4444,
 'ageGradedTotalPlaces': 30701,
 'countryTotalPlaces': 959}